[package]
name = "franzide"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.77"

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
